export const ROLAMENTOS = [
  { categoria: "ROLAMENTO", codigo: "6000", interna: 10, externa: 26, largura: 8, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6001", interna: 12, externa: 28, largura: 8, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6002", interna: 15, externa: 32, largura: 9, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6003", interna: 17, externa: 35, largura: 10, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6004", interna: 20, externa: 42, largura: 12, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6005", interna: 25, externa: 47, largura: 12, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6006", interna: 30, externa: 55, largura: 13, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6200", interna: 10, externa: 30, largura: 9, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6201", interna: 12, externa: 32, largura: 10, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6202", interna: 15, externa: 35, largura: 11, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6203", interna: 17, externa: 40, largura: 12, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6204", interna: 20, externa: 47, largura: 14, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6205", interna: 25, externa: 52, largura: 15, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6206", interna: 30, externa: 62, largura: 16, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6207", interna: 35, externa: 72, largura: 17, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6208", interna: 40, externa: 80, largura: 18, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6300", interna: 10, externa: 35, largura: 11, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6301", interna: 12, externa: 37, largura: 12, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6302", interna: 15, externa: 42, largura: 13, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6303", interna: 17, externa: 47, largura: 14, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6304", interna: 20, externa: 52, largura: 15, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6305", interna: 25, externa: 62, largura: 17, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6306", interna: 30, externa: 72, largura: 19, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6307", interna: 35, externa: 80, largura: 21, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "6308", interna: 40, externa: 90, largura: 23, tipo: "Rigido de esferas" },
  { categoria: "ROLAMENTO", codigo: "30203", interna: 17, externa: 40, largura: 13.25, tipo: "Rolo conico" },
  { categoria: "ROLAMENTO", codigo: "30204", interna: 20, externa: 47, largura: 15.25, tipo: "Rolo conico" },
  { categoria: "ROLAMENTO", codigo: "30205", interna: 25, externa: 52, largura: 16.25, tipo: "Rolo conico" },
  { categoria: "ROLAMENTO", codigo: "30302", interna: 15, externa: 42, largura: 14.25, tipo: "Rolo conico" },
  { categoria: "ROLAMENTO", codigo: "32005X", interna: 25, externa: 47, largura: 15, tipo: "Rolo conico" }
];

export const RETENTORES = [
  { categoria: "RETENTOR", codigo: "TC 10x22x7", interna: 10, externa: 22, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 12x24x7", interna: 12, externa: 24, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 12x28x7", interna: 12, externa: 28, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 15x28x7", interna: 15, externa: 28, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 15x30x7", interna: 15, externa: 30, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 15x32x7", interna: 15, externa: 32, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 17x30x7", interna: 17, externa: 30, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 17x35x7", interna: 17, externa: 35, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 17x40x7", interna: 17, externa: 40, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 17x40x10", interna: 17, externa: 40, largura: 10, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 20x35x7", interna: 20, externa: 35, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 20x40x7", interna: 20, externa: 40, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 20x42x7", interna: 20, externa: 42, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 20x47x7", interna: 20, externa: 47, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 22x35x7", interna: 22, externa: 35, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 25x42x7", interna: 25, externa: 42, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 25x47x7", interna: 25, externa: 47, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 25x52x7", interna: 25, externa: 52, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 25x52x10", interna: 25, externa: 52, largura: 10, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 28x47x7", interna: 28, externa: 47, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 30x47x7", interna: 30, externa: 47, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 30x52x7", interna: 30, externa: 52, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 30x55x8", interna: 30, externa: 55, largura: 8, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 30x62x8", interna: 30, externa: 62, largura: 8, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 32x47x7", interna: 32, externa: 47, largura: 7, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 35x55x8", interna: 35, externa: 55, largura: 8, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 35x62x8", interna: 35, externa: 62, largura: 8, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 35x72x8", interna: 35, externa: 72, largura: 8, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 40x62x8", interna: 40, externa: 62, largura: 8, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 40x72x8", interna: 40, externa: 72, largura: 8, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 40x80x10", interna: 40, externa: 80, largura: 10, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 45x65x8", interna: 45, externa: 65, largura: 8, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 45x72x8", interna: 45, externa: 72, largura: 8, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 50x72x8", interna: 50, externa: 72, largura: 8, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TC 50x80x10", interna: 50, externa: 80, largura: 10, tipo: "TC - Borracha NBR com mola" },
  { categoria: "RETENTOR", codigo: "TB 17x40x10", interna: 17, externa: 40, largura: 10, tipo: "TB - Aco externo + borracha" },
  { categoria: "RETENTOR", codigo: "TB 20x47x10", interna: 20, externa: 47, largura: 10, tipo: "TB - Aco externo + borracha" },
  { categoria: "RETENTOR", codigo: "TB 25x52x10", interna: 25, externa: 52, largura: 10, tipo: "TB - Aco externo + borracha" },
  { categoria: "RETENTOR", codigo: "VC 17x40x7", interna: 17, externa: 40, largura: 7, tipo: "VC - Labio duplo" },
  { categoria: "RETENTOR", codigo: "VC 20x47x7", interna: 20, externa: 47, largura: 7, tipo: "VC - Labio duplo" },
  { categoria: "RETENTOR", codigo: "SC 25x52x7", interna: 25, externa: 52, largura: 7, tipo: "SC - Totalmente metalico" },
  { categoria: "RETENTOR", codigo: "SC 30x62x8", interna: 30, externa: 62, largura: 8, tipo: "SC - Totalmente metalico" }
];

export const DB = [...ROLAMENTOS, ...RETENTORES];
